[package]
name = "fpa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
serde = { version = "1.0.192", features = ["derive"] }
tokio = { version = "1.34.0", features = ["full"] }
utoipa = { version = "4.1.0", features = ["axum_extras"] }
utoipa-rapidoc = { version = "1.0.0", features = ["axum"] }
utoipa-swagger-ui = { version = "4.0.0", features = ["axum"] }

[dev-dependencies]
httpc-test = { version = "0.1.8", features = ["color-output"] }
anyhow = "1.0.75"
