jwks: 
  - http://oauth-2:8080/realms/default/protocol/openid-connect/certs
  - http://oauth-2:8080/realms/tenant-01/protocol/openid-connect/certs
  - http://oauth-2:8080/realms/tenant-02/protocol/openid-connect/certs
  
database:
  engine: postgres
  server: database
  port: 5432
  username: fpa-user
  password: fpa-pass
  name: fpa-management
  connections_max: 100
  connections_min: 5
  timeout_connect: 10
  timeout_acquire: 10
  timeout_idle: 10
  lifetime: 30

scheme: HTTP
authority: oauth-2
port: 5000

empiricals: 
  productivity: 14
  coordination: 20
  deployment: 10
  planning: 15
  testing: 20