services:
  database:
    build: ./database
    ports:
      - 5432:5432
  oauth-2:
    build: ./oauth-2
    ports:
      - 8080:8080
      - 8443:8443
  fpa-server:
    build: ./fpa-server
    ports: 
      - 5000:5000
  fpa-client:
    build: ./fpa-client
    ports:
      - 80:80
