//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "empiricals")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub empirical: i32,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::projects_empiricals::Entity")]
    ProjectsEmpiricals,
}

impl Related<super::projects_empiricals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsEmpiricals.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
