//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::Factor;
use super::sea_orm_active_enums::Influence;
use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

/// Adjustments Factors for the Project.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, ToSchema)]
#[sea_orm(table_name = "factors")]
#[schema(as=Factor)]
#[serde(rename = "Factor")] 
pub struct Model {
    /// Project identifier.
    #[sea_orm(primary_key, auto_increment = false)]
    pub project: Uuid,
    /// Adjustment Fator for the Project.
    #[sea_orm(primary_key, auto_increment = false)]
    pub factor: Factor,
    /// Tenant owner of the Project.
    #[serde(skip)]
    pub tenant: Uuid,
    /// Influence value for the factor on this project.
    pub influence: Influence,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::Project",
        to = "super::projects::Column::Project",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::Tenant",
        to = "super::tenants::Column::Tenant",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tenants,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
