//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "influences")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub influence: i32,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::projects_factors::Entity")]
    ProjectsFactors,
}

impl Related<super::projects_factors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsFactors.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
