//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod alrs;
pub mod empiricals;
pub mod factors;
pub mod functions;
pub mod functions_types;
pub mod modules;
pub mod projects;
pub mod rlrs;
pub mod sea_orm_active_enums;
pub mod tenants;
pub mod users;
pub mod versions;

pub mod page;