//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::tenants::Entity as Tenants;
pub use super::tenants_status::Entity as TenantsStatus;
pub use super::tenants_tier::Entity as TenantsTier;
pub use super::tests::Entity as Tests;
pub use super::users::Entity as Users;
pub use super::versions::Entity as Versions;
