//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::alrs::Entity as Alrs;
pub use super::empiricals::Entity as Empiricals;
pub use super::factors::Entity as Factors;
pub use super::functions::Entity as Functions;
pub use super::functions_types::Entity as FunctionsTypes;
pub use super::influences::Entity as Influences;
pub use super::modules::Entity as Modules;
pub use super::projects::Entity as Projects;
pub use super::projects_empiricals::Entity as ProjectsEmpiricals;
pub use super::projects_factors::Entity as ProjectsFactors;
pub use super::rlrs::Entity as Rlrs;
pub use super::tenants::Entity as Tenants;
pub use super::tenants_status::Entity as TenantsStatus;
pub use super::tenants_tier::Entity as TenantsTier;
pub use super::users::Entity as Users;
pub use super::versions::Entity as Versions;
