//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::alrs::Entity as Alrs;
pub use super::empiricals::Entity as Empiricals;
pub use super::factors::Entity as Factors;
pub use super::functions::Entity as Functions;
pub use super::functions_types::Entity as FunctionsTypes;
pub use super::modules::Entity as Modules;
pub use super::projects::Entity as Projects;
pub use super::rlrs::Entity as Rlrs;
pub use super::tenants::Entity as Tenants;
pub use super::users::Entity as Users;
pub use super::versions::Entity as Versions;
