//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "projects_factors")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub project: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub factor: i32,
    pub tenant: Uuid,
    pub influence: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::factors::Entity",
        from = "Column::Factor",
        to = "super::factors::Column::Factor",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Factors,
    #[sea_orm(
        belongs_to = "super::influences::Entity",
        from = "Column::Influence",
        to = "super::influences::Column::Influence",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Influences,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::Project",
        to = "super::projects::Column::Project",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::Tenant",
        to = "super::tenants::Column::Tenant",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tenants,
}

impl Related<super::factors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Factors.def()
    }
}

impl Related<super::influences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Influences.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
