//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tenants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tenant: Uuid,
    pub name: Option<String>,
    pub time: Option<Time>,
    pub status: i32,
    pub tier: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tenants_status::Entity",
        from = "Column::Status",
        to = "super::tenants_status::Column::Status",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TenantsStatus,
    #[sea_orm(
        belongs_to = "super::tenants_tier::Entity",
        from = "Column::Tier",
        to = "super::tenants_tier::Column::Tier",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TenantsTier,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
}

impl Related<super::tenants_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantsStatus.def()
    }
}

impl Related<super::tenants_tier::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantsTier.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
