//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde_derive::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, ToSchema)]
#[sea_orm(table_name = "versions")]
#[schema(as=Version)]
#[serde(rename = "Version")] 
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub version: Uuid,
    pub name: String,
    pub major: i32,
    pub minor: i32,
    pub build: i32,
    pub time: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
